pro_stages_accueil:
    path: /
    controller: App\Controller\ProStagesController::index
pro_stages_entreprises:
    path: /entreprises
    controller: App\Controller\ProStagesController::entreprises
